// =============================================================================
// src/agent/mod.rs  —  Operation Babel: Agent Module Registry
// =============================================================================
//
// LEARNING TOPIC: Rust Module System — Exposing Submodules
// ---------------------------------------------------------
// This file declares the public submodules of the `agent` crate module.
// The compiler looks for src/agent/joints.rs, src/agent/humanoid.rs, etc.
//
// PUBLIC vs PRIVATE submodules:
//   `pub mod humanoid;`  → everything marked `pub` in humanoid.rs is accessible
//                          from outside the `agent` module (e.g., from lib.rs).
//   `mod internal;`      → only accessible within the `agent` module.
//
// This module also defines the UiAgentCommand enum — the agent-specific
// counterpart to UiCommand in wgpu_view.rs. The same Command Pattern is used:
// the egui UI generates UiAgentCommand values, lib.rs reads them and
// calls the appropriate agent API.
//
// SPRINT ROADMAP for this module:
//   Sprint 5 (now):    joints.rs, humanoid.rs, sensors.rs — box model, 8 joints
//   Sprint 6 (later):  sensors.rs extended with 64-ray Lidar implementation
//   Sprint 11 (later): parallelism — multiple WorldInstance per CPU core
// =============================================================================

pub mod humanoid;
pub mod joints;
pub mod sensors;

use glam::Vec3;

// Re-export the most-used types at the module level for clean import paths.
// Instead of `crate::agent::humanoid::HumanoidRig`, callers write `crate::agent::HumanoidRig`.
pub use humanoid::{
    HumanoidRegistry, HumanoidRig, SpawnHumanoidParams, apply_torque_to_joint,
    collect_humanoid_observation, despawn_all_humanoids, move_humanoid, spawn_humanoid,
    update_humanoid_rigs_system,
};
pub use joints::{
    BodySegment, JOINT_OBSERVATION_STRIDE, JointBodyProperties, JointConstraint,
    apply_joint_torques_system, solve_joint_constraints_system,
};
pub use sensors::{HumanoidSensors, SENSOR_OBSERVATION_STRIDE, update_humanoid_sensors_system};

// =============================================================================
// UiAgentCommand — Intent objects generated by the right-side agent control panel
// =============================================================================
//
// LEARNING: Same Command Pattern as UiCommand in wgpu_view.rs.
// The egui right-side panel generates these commands when the user interacts with
// the agent control panel. Commands are collected into a Vec, then after rendering
// lib.rs processes them and calls the appropriate agent API.
//
// This strict separation means:
//   - The render thread never touches Bevy ECS directly
//   - No data races (render reads ECS, ECS writes are deferred to commands)
//   - The agent control panel is completely decoupled from physics logic
#[derive(Debug, Clone)]
pub enum UiAgentCommand {
    /// Spawn a new humanoid agent at the current spawn target position (spawn_x, spawn_z).
    SpawnHumanoid,

    /// Despawn all currently spawned humanoid agents.
    DespawnAllHumanoids,

    /// Apply a target angle to a specific joint of agent 0 (the most recently spawned).
    /// `segment` — which body segment's joint to control.
    /// `target_angle_radians` — desired angle.
    SetJointAngle {
        segment: BodySegment,
        target_angle_radians: f32,
    },

    /// Set a full pose preset (all joint angles at once).
    ApplyPosePreset { preset: HumanoidPosePreset },

    /// Apply a high-level horizontal movement impulse to the active Worker.
    MoveActiveHumanoid { direction: Vec3 },
}

// =============================================================================
// HumanoidPosePreset — Named pose configurations for the UI control panel
// =============================================================================
//
// LEARNING: Pose presets let the user quickly test the agent's range of motion
// without manually adjusting 8 individual sliders. Each preset sets all joints
// to anatomically meaningful angles.
//
// These are also useful for debugging the joint solver: if "Standing" doesn't
// produce an upright agent, the joint constraint is broken.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum HumanoidPosePreset {
    /// All joints at zero angle — straight limbs.
    TeeStance,

    /// Anatomical standing pose — slight knee flex, arms hanging.
    Standing,

    /// Walking mid-stride — left leg forward, right leg back.
    WalkMidStride,

    /// Deep squat — knees at maximum flex, arms forward for balance.
    Squat,

    /// One-arm reach — right arm extended upward, useful for block placement.
    ArmRaise,
}

impl HumanoidPosePreset {
    /// Human-readable label for the egui dropdown selector.
    pub fn display_label(self) -> &'static str {
        match self {
            HumanoidPosePreset::TeeStance => "T-Stance",
            HumanoidPosePreset::Standing => "Standing",
            HumanoidPosePreset::WalkMidStride => "Walk Stride",
            HumanoidPosePreset::Squat => "Deep Squat",
            HumanoidPosePreset::ArmRaise => "Arm Raise",
        }
    }

    /// Joint angle configuration for this pose.
    /// Returns a slice of (BodySegment, target_angle_radians) pairs.
    ///
    /// LEARNING: Only joints WITH a JointConstraint component are listed.
    /// (Torso has no parent joint, so it's not included.)
    pub fn joint_angles(self) -> &'static [(BodySegment, f32)] {
        match self {
            HumanoidPosePreset::TeeStance => &[
                (BodySegment::LeftThigh, 0.0),
                (BodySegment::LeftShin, 0.0),
                (BodySegment::RightThigh, 0.0),
                (BodySegment::RightShin, 0.0),
                (BodySegment::LeftUpperArm, 0.0),
                (BodySegment::LeftForearm, 0.0),
                (BodySegment::RightUpperArm, 0.0),
                (BodySegment::RightForearm, 0.0),
            ],
            HumanoidPosePreset::Standing => &[
                (BodySegment::LeftThigh, 0.1),
                (BodySegment::LeftShin, 0.15),
                (BodySegment::RightThigh, 0.1),
                (BodySegment::RightShin, 0.15),
                (BodySegment::LeftUpperArm, 0.3),
                (BodySegment::LeftForearm, 0.2),
                (BodySegment::RightUpperArm, 0.3),
                (BodySegment::RightForearm, 0.2),
            ],
            HumanoidPosePreset::WalkMidStride => &[
                (BodySegment::LeftThigh, 0.6), // left leg forward
                (BodySegment::LeftShin, 0.3),
                (BodySegment::RightThigh, -0.4), // right leg back (hip = ball socket, negative = back)
                (BodySegment::RightShin, 1.0),   // right knee bent as leg swings back
                (BodySegment::LeftUpperArm, 0.5),
                (BodySegment::LeftForearm, 0.4),
                (BodySegment::RightUpperArm, -0.5),
                (BodySegment::RightForearm, 0.3),
            ],
            HumanoidPosePreset::Squat => &[
                (BodySegment::LeftThigh, 0.8),
                (BodySegment::LeftShin, 1.8),
                (BodySegment::RightThigh, 0.8),
                (BodySegment::RightShin, 1.8),
                (BodySegment::LeftUpperArm, 0.5),
                (BodySegment::LeftForearm, 0.3),
                (BodySegment::RightUpperArm, 0.5),
                (BodySegment::RightForearm, 0.3),
            ],
            HumanoidPosePreset::ArmRaise => &[
                (BodySegment::LeftThigh, 0.1),
                (BodySegment::LeftShin, 0.15),
                (BodySegment::RightThigh, 0.1),
                (BodySegment::RightShin, 0.15),
                (BodySegment::LeftUpperArm, 0.3),
                (BodySegment::LeftForearm, 0.2),
                (BodySegment::RightUpperArm, 1.4), // right shoulder: arm raised high
                (BodySegment::RightForearm, 0.5),  // right elbow: slightly bent
            ],
        }
    }
}
